# Generated by Django 5.0.7 on 2024-07-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):  # pylint: disable=too-few-public-methods

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('pages', models.IntegerField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
